### ISSUE TITLE
Epic referencing other issues

### ISSUE THREAD

**Issue by nikku** [nikku/testtest#120]
__What should we do?__

* [ ] Check out https://github.com/nikku/testtest/issues/118#issuecomment-1271223336
* [ ] Is  https://github.com/nikku/testtest/pull/82/commits/ff859a123b95377186900829eeebd1a6dd7ee1ee#r989781035 still valid?
* [ ] https://github.com/nikku/testtest/issues/119
* [ ] NOOasd asd asd (
* [ ] SEE YO https://github.com/nikku/testtest/issues/79#issuecomment-1332081654
* [ ] https://github.com/nikku/testtest/issues/120
* [ ] Related to https://github.com/nikku/testtest/commit/ff859a123b95377186900829eeebd1a6dd7ee1ee#r989781035
* [ ] See https://github.com/nikku/testtest/pull/112#issuecomment-1332098253

__Why should we do it?__

See also https://github.com/nikku/testtest/issues/79#issuecomment-1332081654.
